### ISSUE TITLE
Can't find example how to verify IPN 

### ISSUE THREAD

**Issue by dopesong** [bitpay/php-bitpay-client#178]
I can't find any example how to verify IPN. :)

**Comment by leonar15** [comment]
According to their documentation (https://bitpay.com/docs/invoice-callbacks), the data that is sent should not be trusted and should instead trigger a call from your sever to the bitpay API.

" Since we are not yet signing these notifications they should not be trusted outright. We recommend verifying these notifications against our API when they are received to make sure the data presented is authentic. "

**Comment by kleetus** [comment]
For verifying the instant payment/post notification (I'll add this to the examples directory):

1. BitPay will send a HTTP POST back to your notification URL. 
2. You should then send an HTTP GET request to BitPay's API with the invoice information to verify that the IPN is authentic, what @leonar15 said ;)

**Comment by dopesong** [comment]
I think there can be added helper method for that.

**Comment by kleetus** [comment]
a helper method for this is outside the scope of this library. This library is intended to be a dependency for other php software. Better to add it there.

**Comment by 3824409A28** [comment]
Hello
