### ISSUE TITLE
It just hangs after $public->generate(); call

### ISSUE THREAD

**Issue by g-p-c-s** [bitpay/php-bitpay-client#197]
I was trying to setup the php client referring to https://help.bitpay.com/8451-Implementation-/bitpay-php-library-usage-tutorial-from-start-creating-keys-to-finish-creating-an-invoice tutorial. While trying to generate the keys it just hangs at `$public->generate();`

After debugging a bit further it seems to be getting stuck at the following line (`PublicKey.php`). No exceptions were thrown.

```
$R = Util::doubleAndAdd(
        '0x'.$this->privateKey->getHex(),
        $point
    );
```

**Here is the version of PHP installed on my server.**
`
PHP 5.5.32 (cli) (built: Feb  4 2016 09:30:35)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.22, Copyright (c) 2002-2016, by ionCube Ltd.
`

**Comment by kleetus** [comment]
Pretty interesting! I am going under the assumption that the php cli version and the php server version would have the same issue.  If this is a linux/bsd system, would you do the following from a bash-like terminal:

ldd $(which php)

If this is a Mac:

otool -L $(which php)

assuming the 5.5.32 version you referred to is first on your $PATH. I am curious what is linked into your binary. If this is too personal, then please tell me how to reproduce your php build in detail (this might be better in the long run).

**Comment by g-p-c-s** [comment]
**ldd $(which php) gives me:**
	linux-vdso.so.1 =>  (0x00007fff3b17f000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007effdb4af000)
	libedit.so.0 => /usr/lib64/libedit.so.0 (0x00007effdb280000)
	libncurses.so.5 => /lib64/libncurses.so.5 (0x00007effdb05d000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007effdad57000)
	libz.so.1 => /lib64/libz.so.1 (0x00007effdab41000)
	librt.so.1 => /lib64/librt.so.1 (0x00007effda938000)
	libm.so.6 => /lib64/libm.so.6 (0x00007effda6b4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007effda4b0000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007effda296000)
	libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007effd9f43000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007effd9cff000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007effd9a17000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007effd97eb000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007effd95e7000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007effd937a000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007effd8f97000)
	libc.so.6 => /lib64/libc.so.6 (0x00007effd8c03000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007effd89e8000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007effd87e5000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007effd85c4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007effdb6ee000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007effd83ad000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007effd8190000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007effd7f85000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007effd7d81000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007effd7b62000)

**Comment by kleetus** [comment]
I am guessing that the culprit is/are the calls into libcrypto from the php openssl wrappers. I don't think this has anything to do with the php version or ioncube. I activated the ioncube zend extension against php 5.6 and did not experience the same issues. 

Just spit-balling, I bet you are using CentOS with a libcrypto that does not support all the elliptic curve crypto necessary for our plugin. Apparently, this library only supports 3 curves, none of which are secp256k1.  

How to detect if my theory is correct:

from a terminal:

`openssl ecparam -list_curves | grep secp256k1`

you should get:

> secp256k1 : SECG curve over a 256 bit prime field

I did see this issue, but I am not sure if your library is affected:

https://github.com/ptudor/centos6-openssl/issues/4

What you can if I am right:

You can compile the latest openssl from their git repo:

 git clone git://git.openssl.org/openssl.git

and compile libcrypto as per their README

**Comment by g-p-c-s** [comment]
**openssl ecparam -list_curves | grep secp256k1** outputs nothing.

Then I did a **yum update openssl.x86_64** after that as well had no luck.

`openssl.x86_64                                                      1.0.1e-42.el6_7.4` is the current version that's installed.

**Comment by kleetus** [comment]
yep, ok mystery solved. 

Doing a 'yum install openssl' won't do much for you since the version of openssl offered by centos is gimped (IMHO). 

I would follow the directions to use the CentOS 6 / openssl backport. This should get you going pretty fast. I gather, from reading their README, that more curves are going to part of the next release (Sept 2016). 

Semi-apropos, not having the kobliz curves supported in a port of a public library that already supports them is very odd. If I was a conspiracy-theorist, I would call that suspicious. I am sure there is a good reason that I am too lazy to find out. Satoshi Nakamoto chose the k1 curve on purpose because it was one that NSA hadn't co-opted. Anyway, sorry for the trouble that you had with this.

**Comment by g-p-c-s** [comment]
I had fallback on your legacy API. But, can an exception be thrown (unless it is actually going into an infinite loop)?

**Comment by kleetus** [comment]
there is a check for openssl, there ought to be a check for the right curves too

**Comment by kleetus** [comment]
I was incorrect in my assessment of this issue. This plugin does not make use of the EC functions within OpenSSL, therefore the crypto lib not having this support was a red herring, I apologize. The most likely culprit of the infinite loop is here:

https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Util/Util.php#L238

If the behavior of the math library (bcmath or gmp) is that the remainder section of result is simply truncated and only the quotient is returned, then this while loop will terminate properly. If this isn't the behavior and the result is rounded; we've got this problem. 

I haven't found a condition in either math library (matching our calls into it) that points to the issue. I've reviewed the source for php 5.5.32 for both bcmath (bc_div and bc_divide). If you are using GMP and not bcmath, then there is a chance that gmp_div isn't aliased to gmp_div_q in which case you could get this problem. It could also be that the last parameter on  gmp_div_q ($round) isn't GMP_ROUND_ZERO in which case would lead to this issue. Whatever the case, I am going to release a small check around this edge case.
