### ISSUE TITLE
Invoice adjustments?

### ISSUE THREAD

**Issue by juouy** [bitpay/php-bitpay-client#235]
https://bitpay.com/api#resource-Invoices

POST /invoices/:invoiceId/adjustments

Is this possible using api? I dont see any method to accept over/under payment using code.

**Comment by pieterpoorthuis** [comment]
There's currently no PHP BitPay library method for accepting over&underpayments.
It's also not on our roadmap, since BitPay is disabling accepting overpayments soon (1 month from now).

The only option for overpayments will be refunding the overpayment amount. The preferred method is to include the buyerEmail when creating the BitPay invoice, so BitPay can send an email to the customer to claim his overpaid amount back.
