### ISSUE TITLE
IPN Url doesnt hit on the payment of Invoice or any other status change

### ISSUE THREAD

**Issue by msethi1980** [bitpay/php-bitpay-client#248]
Hi,

I have set the IPN Url (https) and also set the flag "fullNotifications" to true but I don't get any control to the URL though the "redirectUrl" works. I have set all the required data including posData, buyer details etc
 The Invoice Id I have used is :
https://test.bitpay.com/invoice?id=5Fmx3rsAesrDk2VsQic7Wf

Can you please help here.

Regards,
Manish

**Comment by pieterpoorthuis** [comment]
Hi,

Your notificationURL is set to https://localhost:8443/... Please use a public domain, since BitPay cannot send notifications to your localhost.
Same holds for your redirectURL. It's set to https://localhost:8443/... Please set it to a public domain, so the client-side browser (that your paying customer is using) can redirect your customer.
